### ISSUE TITLE
postcss-replace with Gulp v4

### ISSUE THREAD

**Issue by benjclark** [gridonic/postcss-replace#6]
I'm having trouble using your plugin because it is not clear from the docs how it should be used.

Could you simply tell me if I am doing this correctly please? It would be incredibly helpful to me.

## css file (input)
```css
.u-text-light{font-weight:100}.u-text-normal{font-weight:400}.u-text-bold{font-weight:700}.u-vh-full{min-height:100vh}
//# sourceMappingURL=main.css.map
```

## gulpfile
```javascript
const postcss = require('gulp-postcss');
const postcssReplace = require('postcss-replace');

gulp.task('simplified-example-task', () => {
    return gulp.src('*.css')
        .pipe(postcss([postcssReplace({
            data: {value: '/*# sourceMappingURL'},
            pattern: '(?:\\/\\/\\#\\ sourceMappingURL)'
        })]))
        .pipe(postcss([postcssReplace({
            data: {value: '.map */'},
            pattern: '/(?:\\.map)/'
        })]))
        .pipe(gulp.dest('.'));
});
```

My aim is to convert `//# sourceMappingURL=main.css.map` to `/*# sourceMappingURL=main.css.map */` in any css file passed in to it.
